name: Integration Tests

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: [ "main", "dev"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  OpenFOAM:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/simvue-io/openfoam_example
    steps:
      - uses: actions/checkout@v4
      - uses: aarcangeli/load-dotenv@v1
        with:
          path: ".github"
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies and run tests
        run: |
          export WM_PROJECT_DIR=/opt/openfoam10
          export SIMVUE_URL=${{ secrets.SIMVUE_URL }}
          export SIMVUE_TOKEN=${{ secrets.SIMVUE_TOKEN }}
          poetry install --with dev
          poetry run pytest tests/integration/
